services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: godo_user
      POSTGRES_PASSWORD: godo_password
      POSTGRES_DB: godo_db
    volumes:
      - db_data:var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
